"""
50 world cuisine profiles — seeded into the cuisines table on first run.
Each entry maps to the Cuisine model fields.
differentiating_factors: what makes this cuisine distinct from similar ones — key signal for sub-profile matching.
"""

CUISINES: list[dict] = [
    # ── East Asia ─────────────────────────────────────────────────────────
    {
        "name": "Japanese",
        "region": "East Asia",
        "description": "Emphasizes seasonal ingredients, umami, and minimal seasoning to let natural flavors shine.",
        "key_ingredients": ["dashi", "miso", "soy sauce", "mirin", "sake", "tofu", "nori", "wasabi"],
        "key_techniques": ["steaming", "grilling (yakitori)", "raw (sashimi/sushi)", "tempura frying"],
        "flavor_profile": {"umami": 5, "sweet": 2, "salty": 3, "sour": 2, "spicy": 1},
        "typical_dishes": ["sushi", "ramen", "tempura", "yakitori", "miso soup", "tonkatsu", "udon", "soba"],
        "differentiating_factors": "Look for dashi-based broths, raw fish preparations, miso/soy/mirin trio, and dishes with Japanese names (ramen, yakitori, tonkatsu). Minimal oil, restrained seasoning, seasonal ethos. NOT spicy. Distinct from Chinese by absence of heavy sauces and wok char.",
    },
    {
        "name": "Chinese (Cantonese)",
        "region": "East Asia",
        "sub_region": "Southern China",
        "description": "Light, fresh flavors; emphasis on seafood and dim sum. Steaming and stir-frying dominate.",
        "key_ingredients": ["oyster sauce", "ginger", "scallion", "soy sauce", "sesame oil", "rice wine"],
        "key_techniques": ["steaming", "stir-fry (wok hei)", "roasting", "blanching"],
        "flavor_profile": {"umami": 4, "sweet": 3, "salty": 3, "sour": 1, "spicy": 1},
        "typical_dishes": ["dim sum", "char siu", "roast duck", "congee", "wonton noodle soup", "steamed fish"],
        "differentiating_factors": "Key signals: dim sum items (har gow, siu mai, char siu bao), roast meats (char siu, roast duck), delicate steamed fish. NOT spicy, NOT bold. Light sauce, natural ingredient flavor. Distinct from Sichuan (no numbing heat) and Shanghai (less sweet, less wine).",
    },
    {
        "name": "Chinese (Sichuan)",
        "region": "East Asia",
        "sub_region": "Southwestern China",
        "description": "Bold, spicy, and numbing from Sichuan peppercorns. Rich use of chili and fermented pastes.",
        "key_ingredients": ["Sichuan peppercorn", "doubanjiang", "dried chili", "garlic", "ginger", "tofu"],
        "key_techniques": ["dry-frying", "braising", "stir-fry", "cold tossing"],
        "flavor_profile": {"umami": 4, "sweet": 1, "salty": 4, "sour": 1, "spicy": 5},
        "typical_dishes": ["mapo tofu", "kung pao chicken", "dan dan noodles", "twice-cooked pork", "hot pot"],
        "differentiating_factors": "THE defining signal is mala (numbing + spicy) from Sichuan peppercorn. Look for doubanjiang (spicy fermented bean paste), mapo tofu, dan dan noodles, hot pot. Spicy score 5/5. Completely different from Cantonese (light/mild) and Shanghai (sweet).",
    },
    {
        "name": "Chinese (Shanghai)",
        "region": "East Asia",
        "sub_region": "Eastern China",
        "description": "Rich and sweet-savory; heavy use of sugar, Shaoxing wine, and slow-braised meats.",
        "key_ingredients": ["Shaoxing wine", "sugar", "soy sauce", "crab roe", "pork belly"],
        "key_techniques": ["red-braising", "steaming", "souping"],
        "flavor_profile": {"umami": 3, "sweet": 4, "salty": 3, "sour": 1, "spicy": 1},
        "typical_dishes": ["xiaolongbao", "red-braised pork", "lion's head meatballs", "scallion oil noodles"],
        "differentiating_factors": "Key signals: xiaolongbao (soup dumplings), red-braised pork belly (hong shao rou), hairy crab roe dishes, sweet-heavy soy glazes. Sweet profile (4/5) from liberal sugar use. Shaoxing wine prominent. NOT spicy.",
    },
    {
        "name": "Korean",
        "region": "East Asia",
        "description": "Fermented, spicy, and banchan-centered communal dining. Grilling at the table is iconic.",
        "key_ingredients": ["gochujang", "doenjang", "kimchi", "sesame", "garlic", "perilla"],
        "key_techniques": ["fermentation", "grilling (KBBQ)", "braising", "pickling"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 3, "spicy": 4},
        "typical_dishes": ["kimchi jjigae", "bibimbap", "Korean BBQ", "tteokbokki", "bulgogi", "sundubu-jjigae"],
        "differentiating_factors": "Look for kimchi (fermented cabbage) as a staple, gochujang (red chili paste), Korean BBQ (grilling at table), banchan (small side dishes). Doenjang (fermented soybean paste) distinct from Japanese miso. Always has sesame oil + garlic + gochujang trinity.",
    },

    # ── Southeast Asia ────────────────────────────────────────────────────
    {
        "name": "Thai (Central)",
        "region": "Southeast Asia",
        "sub_region": "Central Thailand",
        "description": "Balanced sweet, sour, salty, spicy. Coconut milk curries and aromatic pastes.",
        "key_ingredients": ["fish sauce", "lemongrass", "galangal", "kaffir lime", "coconut milk", "Thai basil"],
        "key_techniques": ["curry paste pounding", "stir-fry", "souping"],
        "flavor_profile": {"umami": 3, "sweet": 3, "salty": 4, "sour": 3, "spicy": 3},
        "typical_dishes": ["pad thai", "green curry", "tom kha", "som tum", "massaman curry"],
        "differentiating_factors": "Classic Thai: pad thai, green/red/massaman curry with coconut milk, tom kha/tom yum soups. Balanced 4-flavor profile. Fish sauce + lemongrass + kaffir lime + Thai basil. This is the 'standard' Thai most people know. Distinct from Northern Thai (no khao soi, not milder) and Isaan (not as funky/fermented).",
    },
    {
        "name": "Thai (Northern)",
        "region": "Southeast Asia",
        "sub_region": "Northern Thailand",
        "description": "Milder and earthier than central Thai; heavy Burmese/Shan influence. Khao soi is the signature dish.",
        "key_ingredients": ["shrimp paste", "turmeric", "ginger", "sticky rice", "fermented soybean"],
        "key_techniques": ["slow braising", "herb-heavy salads", "fermentation"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["khao soi", "sai oua", "larb moo", "nam prik noom", "kanom jeen"],
        "differentiating_factors": "THE signature dish is khao soi (coconut curry noodle soup with crispy noodles on top). Also: sai oua (herbal sausage), nam prik noom (roasted green chili dip), sticky rice, milder spice. Burmese/Shan influence. If khao soi is on the menu = Northern Thai. Less coconut milk than Central, less funky than Isaan.",
    },
    {
        "name": "Thai (Northeastern / Isaan)",
        "region": "Southeast Asia",
        "sub_region": "Northeastern Thailand",
        "description": "Bold, funky, and fiery with Lao influences. Heavy fermented fish and raw-meat preparations.",
        "key_ingredients": ["padaek (fermented fish)", "sticky rice", "toasted rice powder", "dried chili"],
        "key_techniques": ["grilling", "larb (tossing with toasted rice powder)", "fermentation"],
        "flavor_profile": {"umami": 5, "sweet": 1, "salty": 4, "sour": 4, "spicy": 5},
        "typical_dishes": ["larb", "som tum (papaya salad)", "grilled chicken (gai yang)", "moo nam tok"],
        "differentiating_factors": "Look for larb (minced meat salad with toasted rice powder + raw blood), som tum (green papaya salad), gai yang (grilled chicken), padaek (fermented fish paste smell). Extremely funky umami (5/5), very spicy (5/5). Raw or near-raw meat dishes. Sticky rice only (no jasmine). Lao-influenced.",
    },
    {
        "name": "Vietnamese",
        "region": "Southeast Asia",
        "description": "Fresh herbs, light broths, and balance of textures. French colonial influence in baguettes and pâté.",
        "key_ingredients": ["fish sauce", "rice noodles", "fresh herbs", "lemongrass", "lime", "star anise"],
        "key_techniques": ["long-simmered broths", "fresh rolling (spring rolls)", "grilling"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 4, "spicy": 2},
        "typical_dishes": ["pho", "banh mi", "bun bo hue", "goi cuon", "cao lau", "banh xeo"],
        "differentiating_factors": "Pho (beef/chicken noodle soup with star anise + cinnamon broth) is the iconic dish. Also banh mi (French baguette sandwich), fresh spring rolls (goi cuon). Very light, herb-forward, minimal oil. French baguette/pâté presence = Vietnamese. Not spicy (2/5). Distinct from Thai by absence of coconut milk curries.",
    },
    {
        "name": "Indonesian",
        "region": "Southeast Asia",
        "description": "Spice-trade legacy; rich peanut sauces, coconut, and complex spice pastes (bumbu).",
        "key_ingredients": ["tempeh", "shrimp paste", "candlenut", "galangal", "kecap manis", "coconut"],
        "key_techniques": ["bumbu (spice paste)", "deep frying", "braising in coconut"],
        "flavor_profile": {"umami": 3, "sweet": 3, "salty": 3, "sour": 2, "spicy": 3},
        "typical_dishes": ["rendang", "nasi goreng", "satay", "gado-gado", "soto ayam", "opor ayam"],
        "differentiating_factors": "Rendang (slow-cooked dry beef in coconut/spices) is the most distinctive dish. Kecap manis (sweet soy sauce) and tempeh are Indonesian-specific. Nasi goreng (fried rice). Peanut sauce on satay/gado-gado. Bumbu (complex spice paste) base for everything.",
    },
    {
        "name": "Filipino",
        "region": "Southeast Asia",
        "description": "Spanish, Malay, and Chinese fusion. Sour-savory (adobo) and sweet-sour profiles dominate.",
        "key_ingredients": ["vinegar", "soy sauce", "calamansi", "pork belly", "bagoong (shrimp paste)"],
        "key_techniques": ["adobo braising", "kare-kare (peanut stewing)", "lechon roasting"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 4, "sour": 4, "spicy": 1},
        "typical_dishes": ["adobo", "sinigang", "lechon", "kare-kare", "sisig", "pancit"],
        "differentiating_factors": "Adobo (vinegar + soy braised meat) and sinigang (tamarind sour soup) are uniquely Filipino. Lechon (whole roasted pig). Kare-kare (oxtail peanut stew + bagoong). NOT spicy. Heavy vinegar/sour profile. Spanish names on dishes (adobo, lechon, tocino).",
    },
    {
        "name": "Singaporean / Malaysian",
        "region": "Southeast Asia",
        "description": "Chinese, Malay, and Indian melting pot. Hawker culture with bold, complex dishes.",
        "key_ingredients": ["coconut milk", "pandan", "sambal", "shrimp paste", "curry leaves"],
        "key_techniques": ["hawker wok cooking", "curry braising", "laksa paste"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 2, "spicy": 4},
        "typical_dishes": ["laksa", "hainanese chicken rice", "char kway teow", "nasi lemak", "chili crab"],
        "differentiating_factors": "Laksa (spicy coconut curry noodle soup) and hainanese chicken rice are the most distinctive. Nasi lemak (coconut rice with sambal + anchovies). Char kway teow (stir-fried flat rice noodles with wok hei). Multi-ethnic: Chinese, Malay, Indian influences on a single menu.",
    },

    # ── South Asia ────────────────────────────────────────────────────────
    {
        "name": "North Indian",
        "region": "South Asia",
        "sub_region": "Northern India",
        "description": "Mughal-influenced; rich, dairy-heavy curries, tandoor cooking, and wheat-based breads.",
        "key_ingredients": ["ghee", "paneer", "cardamom", "cumin", "yogurt", "cream", "saffron"],
        "key_techniques": ["tandoor", "dum (slow-pot)", "tarka (tempering spices)"],
        "flavor_profile": {"umami": 2, "sweet": 2, "salty": 3, "sour": 2, "spicy": 3},
        "typical_dishes": ["butter chicken", "biryani", "dal makhani", "rogan josh", "naan", "saag paneer"],
        "differentiating_factors": "Butter chicken, naan, dal makhani, biryani, tandoori dishes. Cream/butter/ghee-heavy sauces. Paneer cheese. Mughal names (biryani, korma, rogan josh). Wheat-based breads (naan, roti, paratha). Distinct from South Indian: NO dosa/idli/sambar, no rice-lentil crepes, less tamarind.",
    },
    {
        "name": "South Indian",
        "region": "South Asia",
        "sub_region": "Southern India",
        "description": "Rice and lentil-centric, coconut-heavy, tamarind-sour. Fermented crepes and chutneys.",
        "key_ingredients": ["coconut", "tamarind", "curry leaves", "mustard seeds", "urad dal", "rice"],
        "key_techniques": ["fermentation (dosa/idli batter)", "tempering", "wet grinding"],
        "flavor_profile": {"umami": 2, "sweet": 1, "salty": 3, "sour": 4, "spicy": 4},
        "typical_dishes": ["dosa", "idli sambar", "rasam", "chettinad chicken", "fish curry", "uttapam"],
        "differentiating_factors": "KEY signals: dosa (fermented rice/lentil crepe) and idli/sambar. Coconut chutney. Curry leaves + mustard seeds tempering. Tamarind-based sourness (rasam soup). Rice-centric, NOT wheat/naan. No cream-heavy sauces. Completely distinct from North Indian: if dosa is on menu = South Indian.",
    },
    {
        "name": "Sri Lankan",
        "region": "South Asia",
        "description": "Intense spicing, black curry powder, and heavy coconut milk. Influenced by Dutch, Portuguese, Tamil.",
        "key_ingredients": ["roasted curry powder", "goraka", "coconut milk", "pandan", "green chili"],
        "key_techniques": ["black curry (roasted spice)", "pol sambol", "hoppers"],
        "flavor_profile": {"umami": 2, "sweet": 2, "salty": 3, "sour": 3, "spicy": 5},
        "typical_dishes": ["fish ambul thiyal", "hoppers", "string hoppers", "kottu roti", "dhal curry"],
        "differentiating_factors": "Hoppers (bowl-shaped fermented rice crepe) and kottu roti (stir-fried flatbread) are uniquely Sri Lankan. Goraka (gamboge) as souring agent. Black curry powder (toasted dark spices) gives a smoky darkness distinct from Indian yellow curry. Extremely spicy (5/5).",
    },

    # ── Middle East & Central Asia ─────────────────────────────────────────
    {
        "name": "Lebanese",
        "region": "Middle East",
        "description": "Fresh, vegetable-forward mezze culture. Olive oil, lemon, and herbs are central.",
        "key_ingredients": ["tahini", "sumac", "za'atar", "pomegranate molasses", "rose water", "freekeh"],
        "key_techniques": ["mezze spread", "charcoal grilling", "slow braising"],
        "flavor_profile": {"umami": 2, "sweet": 2, "salty": 3, "sour": 4, "spicy": 2},
        "typical_dishes": ["hummus", "fattoush", "kibbeh", "shawarma", "tabbouleh", "manakish"],
        "differentiating_factors": "Tabbouleh (parsley-heavy bulgur salad), kibbeh (bulgur + lamb), manakish (za'atar flatbread). Very herb-forward and fresh. Pomegranate molasses in dressings. Distinct from Turkish (less kebab-forward) and Israeli (less eggs/shakshuka). Fattoush with sumac is key.",
    },
    {
        "name": "Persian (Iranian)",
        "region": "Middle East",
        "description": "Sweet-sour balance, saffron, pomegranate, and herb-rice khoresh stews.",
        "key_ingredients": ["saffron", "dried limes", "pomegranate", "walnuts", "barberries", "fenugreek"],
        "key_techniques": ["khoresh (stewing)", "polo (jeweled rice)", "kebab grilling"],
        "flavor_profile": {"umami": 2, "sweet": 3, "salty": 2, "sour": 4, "spicy": 1},
        "typical_dishes": ["ghormeh sabzi", "fesenjan", "tahdig", "koofteh", "kebab koobideh", "ash reshteh"],
        "differentiating_factors": "Saffron rice (tahdig = crispy rice crust) is uniquely Persian. Fesenjan (walnut + pomegranate stew). Ghormeh sabzi (herb stew with dried limes). Barberries (zereshk) as garnish. Very sweet-sour (sweet 3, sour 4). NOT spicy (1/5). If tahdig or fesenjan = definitely Persian.",
    },
    {
        "name": "Turkish",
        "region": "Middle East",
        "description": "Ottoman heritage spanning sweet pastries to smoky kebabs; yogurt, sumac, and meze.",
        "key_ingredients": ["yogurt", "bulgur", "red pepper paste", "sumac", "lamb", "sesame"],
        "key_techniques": ["mangal grilling", "börek pastry", "slow braising"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["kebab", "meze", "pide", "lahmacun", "köfte", "börek", "baklava"],
        "differentiating_factors": "Börek (flaky pastry with cheese/meat), pide (Turkish flatbread pizza), lahmacun (thin meat flatbread), köfte (spiced ground meat). Yogurt served alongside everything. Baklava for dessert. Ottoman opulence. Distinct from Lebanese: more bread/pastry-forward, less fresh herbs.",
    },
    {
        "name": "Israeli",
        "region": "Middle East",
        "description": "Confluence of Ashkenazi, Sephardic, Yemeni, and Arab traditions; vegetable-forward.",
        "key_ingredients": ["tahini", "za'atar", "harissa", "preserved lemon", "amba", "chickpeas"],
        "key_techniques": ["shakshuka (egg-braising)", "falafel frying", "mezze spreading"],
        "flavor_profile": {"umami": 2, "sweet": 2, "salty": 3, "sour": 3, "spicy": 2},
        "typical_dishes": ["shakshuka", "sabich", "falafel", "hummus", "Israeli salad", "jachnun"],
        "differentiating_factors": "Shakshuka (eggs poached in tomato sauce) is the most distinctive Israeli dish. Sabich (fried eggplant + egg in pita). Amba (mango pickle). Multi-cultural mix: Yemeni jachnun, Sephardic dishes, Arab-influenced mezze. Amba sauce = strong Israeli signal.",
    },

    # ── African ───────────────────────────────────────────────────────────
    {
        "name": "Ethiopian / Eritrean",
        "region": "East Africa",
        "description": "Injera-centered communal eating. Berbere and mitmita spice blends are defining.",
        "key_ingredients": ["injera (teff)", "berbere", "niter kibbeh", "fenugreek", "korarima"],
        "key_techniques": ["tibs (sauté)", "kitfo (raw beef)", "wot (stew)"],
        "flavor_profile": {"umami": 2, "sweet": 1, "salty": 3, "sour": 3, "spicy": 4},
        "typical_dishes": ["doro wot", "tibs", "kitfo", "shiro", "misir wot", "injera"],
        "differentiating_factors": "Injera (spongy fermented teff flatbread used as plate + utensil) is completely unique. Berbere spice blend. Doro wot (chicken stew). Kitfo (Ethiopian steak tartare). Communal serving on a single large injera. No utensils used. Immediately identifiable.",
    },
    {
        "name": "West African",
        "region": "West Africa",
        "description": "Palm oil, fermented locust beans, and peanuts base many stews. Jollof rice is iconic.",
        "key_ingredients": ["palm oil", "egusi", "okra", "scotch bonnet", "dawadawa", "plantain"],
        "key_techniques": ["suya grilling", "long stewing", "frying"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 1, "spicy": 4},
        "typical_dishes": ["jollof rice", "egusi soup", "suya", "fufu", "peanut soup", "mofongo"],
        "differentiating_factors": "Jollof rice (tomato-stewed rice), egusi soup (ground melon seed stew with palm oil), fufu (pounded starchy dough), suya (spiced grilled meat skewers). Palm oil redness is visual signal. Plantain dishes. Scotch bonnet heat.",
    },
    {
        "name": "North African (Moroccan)",
        "region": "North Africa",
        "description": "Berber, Arab, and Andalusian fusion. Sweet-savory tagines, preserved lemons, harissa.",
        "key_ingredients": ["ras el hanout", "preserved lemon", "argan oil", "harissa", "couscous", "saffron"],
        "key_techniques": ["tagine slow-cooking", "bastilla pastry", "mechoui roasting"],
        "flavor_profile": {"umami": 2, "sweet": 3, "salty": 3, "sour": 3, "spicy": 2},
        "typical_dishes": ["tagine", "couscous", "bastilla", "harira", "merguez", "msemen"],
        "differentiating_factors": "Tagine (conical clay pot slow-cooked stew with preserved lemon + olives) and couscous are the main identifiers. Bastilla (pigeon/chicken in flaky pastry with powdered sugar). Ras el hanout spice blend. Preserved lemon is key. Sweet-savory combination (dates + lamb in same dish).",
    },

    # ── Europe ────────────────────────────────────────────────────────────
    {
        "name": "Italian",
        "region": "Europe",
        "description": "Regional diversity underpins Italian cooking. Pasta, olive oil, tomato, and aged cheese.",
        "key_ingredients": ["pasta", "olive oil", "tomato", "parmigiano", "basil", "prosciutto", "burrata"],
        "key_techniques": ["pasta-making", "risotto stirring", "wood-fired pizza"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 2, "spicy": 1},
        "typical_dishes": ["pasta carbonara", "risotto", "pizza", "bistecca", "osso buco", "tiramisu"],
        "differentiating_factors": "Pasta (fresh or dried) and pizza are universal Italian signals. Parmigiano-Reggiano, burrata, prosciutto. Risotto. Tiramisu for dessert. Simple ingredient combinations (carbonara = eggs + guanciale + pecorino only). NOT spicy. Olive oil everywhere.",
    },
    {
        "name": "French",
        "region": "Europe",
        "description": "Classical technique-driven cuisine; mother sauces, terroir, and charcuterie.",
        "key_ingredients": ["butter", "cream", "wine", "herbes de Provence", "shallots", "foie gras"],
        "key_techniques": ["sauce-making", "confit", "sous vide", "braising"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 2, "spicy": 1},
        "typical_dishes": ["bouillabaisse", "duck confit", "coq au vin", "steak tartare", "croissant", "soufflé"],
        "differentiating_factors": "Mother sauces (beurre blanc, béarnaise, beurre rouge). Confit duck. Foie gras. Coq au vin. Steak tartare. Croissant/éclair for pastry. French wine in cooking. Classical technique vocabulary (confit, en papillote, sous vide). Fine dining tasting menu = likely French-influenced.",
    },
    {
        "name": "Spanish",
        "region": "Europe",
        "description": "Tapas culture, Moorish spice legacy, and seafood. Jamón and olive oil are pillars.",
        "key_ingredients": ["saffron", "pimentón", "jamón", "olive oil", "sherry", "Manchego"],
        "key_techniques": ["paella (socarrat)", "pintxos assembly", "churro frying"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["paella", "gazpacho", "tortilla española", "jamón ibérico", "croquetas", "patatas bravas"],
        "differentiating_factors": "Paella (saffron rice with socarrat crust) and jamón ibérico are the clearest signals. Tapas/pintxos format (small plates). Gazpacho (cold tomato soup). Pimentón (smoked paprika) in almost everything. Churros. Sherry in cooking.",
    },
    {
        "name": "Greek",
        "region": "Europe",
        "description": "Mediterranean diet cornerstone: olive oil, legumes, grilled meats, and phyllo pastry.",
        "key_ingredients": ["olive oil", "feta", "oregano", "lemon", "lamb", "phyllo", "kalamata olives"],
        "key_techniques": ["gyros spit-roasting", "spanakopita baking", "grilling (souvlaki)"],
        "flavor_profile": {"umami": 2, "sweet": 2, "salty": 3, "sour": 3, "spicy": 1},
        "typical_dishes": ["moussaka", "souvlaki", "spanakopita", "tzatziki", "saganaki", "baklava"],
        "differentiating_factors": "Feta cheese (salty, crumbly) in everything. Moussaka (eggplant + meat + béchamel). Spanakopita (spinach + feta in phyllo). Tzatziki (yogurt + cucumber + garlic). Saganaki (fried cheese). Lemon + oregano on everything. Gyros.",
    },
    {
        "name": "Scandinavian",
        "region": "Europe",
        "description": "New Nordic movement: foraged, cured, and fermented with extreme seasonality.",
        "key_ingredients": ["dill", "aquavit", "lingonberry", "cured salmon", "rye", "cloudberry"],
        "key_techniques": ["curing", "smoking", "fermenting", "foraging"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 4, "sour": 3, "spicy": 1},
        "typical_dishes": ["gravlax", "smørrebrød", "frikadeller", "pickled herring", "lefse", "æbleskiver"],
        "differentiating_factors": "Gravlax (dill-cured salmon). Smørrebrød (open-faced rye sandwich). Pickled herring. Lingonberry jam. Dill on everything. New Nordic tasting menu style (foraged, hyper-seasonal, fermented). Aquavit as spirit. Extremely minimalist presentation.",
    },
    {
        "name": "British / Irish",
        "region": "Europe",
        "description": "Comfort-driven; roasts, pies, and pub classics. Strong South Asian influence via curry.",
        "key_ingredients": ["butter", "Worcestershire sauce", "malt vinegar", "stilton", "lamb", "oats"],
        "key_techniques": ["roasting", "braising", "pie-making"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 2, "spicy": 1},
        "typical_dishes": ["fish and chips", "Sunday roast", "shepherd's pie", "full English breakfast", "scotch egg"],
        "differentiating_factors": "Fish and chips (with malt vinegar). Full English breakfast (eggs, beans, sausage, toast). Sunday roast with Yorkshire pudding. Shepherd's/cottage pie. Scotch egg. Stilton cheese. Pub food format. Worcestershire sauce.",
    },
    {
        "name": "Eastern European",
        "region": "Europe",
        "description": "Hearty, fermented, and pork-forward. Pierogi, borscht, and cured meats dominate.",
        "key_ingredients": ["sour cream", "beets", "dill", "pork", "caraway", "horseradish", "rye"],
        "key_techniques": ["pickling", "slow braising", "dumpling folding"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 4, "sour": 4, "spicy": 1},
        "typical_dishes": ["pierogi", "borscht", "goulash", "schnitzel", "kielbasa", "stuffed cabbage"],
        "differentiating_factors": "Pierogi (stuffed dumplings with potato/cheese/meat). Borscht (beet soup, red or clear). Kielbasa sausage. Schnitzel. Sour cream on everything. Pickled everything. Beets are key visual signal. Caraway in bread and sauerkraut.",
    },

    # ── The Americas ──────────────────────────────────────────────────────
    {
        "name": "Mexican",
        "region": "Latin America",
        "description": "Pre-Columbian and Spanish fusion. Chili, corn, and chocolate are foundational.",
        "key_ingredients": ["chili (dried)", "corn (masa)", "epazote", "chocolate", "tomatillo", "cilantro"],
        "key_techniques": ["nixtamalization", "molcajete grinding", "comal grilling"],
        "flavor_profile": {"umami": 2, "sweet": 2, "salty": 3, "sour": 3, "spicy": 4},
        "typical_dishes": ["tacos", "mole negro", "pozole", "chiles en nogada", "tamales", "birria"],
        "differentiating_factors": "Tacos (corn tortilla), mole negro (chocolate + chili sauce), birria (braised goat/beef), tamales, pozole (hominy stew). Masa (nixtamalized corn) in everything. Tomatillo (green salsa). Dried chili varieties (ancho, guajillo, chipotle). NOT Tex-Mex (no cheese-smothered dishes).",
    },
    {
        "name": "Peruvian",
        "region": "Latin America",
        "description": "One of the world's most biodiverse cuisines. Japanese and Chinese (Chifa) fusion, ceviche, and potato diversity.",
        "key_ingredients": ["aji amarillo", "huacatay", "quinoa", "purple corn", "lucuma", "tiradito fish"],
        "key_techniques": ["leche de tigre (citrus cure)", "anticucho grilling", "Nikkei fusion"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 5, "spicy": 3},
        "typical_dishes": ["ceviche", "lomo saltado", "causa", "anticucho", "aji de gallina", "tiradito"],
        "differentiating_factors": "Ceviche (citrus-cured fish with leche de tigre + aji amarillo) is the clearest signal. Lomo saltado (stir-fried beef with soy + french fries = Nikkei influence). Aji amarillo (yellow chili) in almost every sauce. Causa (cold potato cake). Anticucho (grilled heart skewers). Most sour cuisine (5/5).",
    },
    {
        "name": "Brazilian",
        "region": "Latin America",
        "description": "Churrasco-centered meat culture with African, Indigenous, and Portuguese layers.",
        "key_ingredients": ["dendê (palm oil)", "manioc", "black beans", "cachaça", "malagueta chili"],
        "key_techniques": ["churrasco grilling", "feijoada slow stewing", "moqueca clay-pot"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["feijoada", "churrasco", "moqueca", "coxinha", "pão de queijo", "brigadeiro"],
        "differentiating_factors": "Churrasco (all-you-can-eat rotisserie meat on swords). Feijoada (black bean + pork stew, national dish). Pão de queijo (cheese bread balls). Moqueca (coconut milk + dendê fish stew). Brigadeiro (chocolate truffle). Caipirinha (cachaça cocktail).",
    },
    {
        "name": "American (BBQ / Southern)",
        "region": "North America",
        "sub_region": "Southern United States",
        "description": "Low-and-slow smoked meats, African and British roots, butter-rich sides.",
        "key_ingredients": ["hickory smoke", "pork ribs", "cornmeal", "buttermilk", "hot sauce", "bourbon"],
        "key_techniques": ["low-and-slow smoking", "cast-iron frying", "biscuit-making"],
        "flavor_profile": {"umami": 4, "sweet": 3, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["brisket", "pulled pork", "fried chicken", "gumbo", "jambalaya", "mac and cheese"],
        "differentiating_factors": "Smoke ring on brisket/ribs, pulled pork sandwiches, fried chicken + biscuits. Gumbo (roux-based stew with okra). Bourbon-based sauces. Cornbread and collard greens as sides. Low-and-slow pit smoking = core identity. Distinct from generic American.",
    },
    {
        "name": "Caribbean",
        "region": "Latin America",
        "description": "African, Amerindian, and European syncretism. Allspice, scotch bonnet, and jerk are signatures.",
        "key_ingredients": ["allspice", "scotch bonnet", "plantain", "thyme", "coconut", "salt cod"],
        "key_techniques": ["jerk marinating and grilling", "roti wrapping", "pelau one-pot"],
        "flavor_profile": {"umami": 2, "sweet": 3, "salty": 3, "sour": 2, "spicy": 4},
        "typical_dishes": ["jerk chicken", "roti", "ackee and saltfish", "rice and peas", "oxtail stew"],
        "differentiating_factors": "Jerk chicken (allspice + scotch bonnet marinade, charcoal grilled) is the most distinctive. Ackee and saltfish (Jamaica's national dish). Roti with curry (Trinidad). Oxtail stew. Rice and peas (coconut milk + kidney beans). Plantain fried or baked.",
    },

    # ── South America (additional) ────────────────────────────────────────
    {
        "name": "Argentine",
        "region": "Latin America",
        "sub_region": "South America",
        "description": "Beef-centric asado culture with Italian immigrant dessert and pasta traditions.",
        "key_ingredients": ["chimichurri", "malbec", "dulce de leche", "provoleta", "beef"],
        "key_techniques": ["parrilla open-fire grilling", "empanada baking", "alfajor making"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 2, "spicy": 1},
        "typical_dishes": ["asado", "empanadas", "chimichurri steak", "milanesa", "provoleta"],
        "differentiating_factors": "Asado (wood-fire grilled beef) with chimichurri sauce is the core identity. Empanadas (baked, not fried). Dulce de leche in desserts. Provoleta (grilled provolone cheese). Malbec wine. Italian immigrant influence in pasta/gelato. NOT spicy at all (1/5).",
    },

    # ── South / Central Asia extras ───────────────────────────────────────
    {
        "name": "Georgian",
        "region": "Caucasus",
        "description": "Walnut-heavy sauces, churchkhela, and supra feast culture. Unique spices like blue fenugreek.",
        "key_ingredients": ["walnuts", "tarragon", "pomegranate", "tkemali (plum sauce)", "fenugreek", "churchkhela"],
        "key_techniques": ["tone (clay oven) baking", "satsivi (walnut sauce)", "khinkali pleating"],
        "flavor_profile": {"umami": 2, "sweet": 2, "salty": 3, "sour": 4, "spicy": 2},
        "typical_dishes": ["khachapuri", "khinkali", "satsivi", "lobiani", "badrijani nigvzit"],
        "differentiating_factors": "Khachapuri (cheese-filled boat bread with egg) is uniquely Georgian. Khinkali (twisted dumplings with soup inside). Walnut sauces on everything. Tkemali (sour plum sauce). Blue fenugreek. Supra (feast) culture. Very distinct from neighboring cuisines.",
    },
    {
        "name": "Uzbek / Central Asian",
        "region": "Central Asia",
        "description": "Silk Road heritage: plov (rice pilaf), lamb, and tandoor bread.",
        "key_ingredients": ["lamb", "cottonseed oil", "cumin", "carrots", "chickpeas", "non (flatbread)"],
        "key_techniques": ["plov (one-pot layering)", "tandoor (nan baking)", "manti steaming"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 1, "spicy": 2},
        "typical_dishes": ["plov", "shashlik", "manti", "lagman", "samsa", "chuchvara"],
        "differentiating_factors": "Plov (lamb + carrot + rice pilaf cooked in kazan/wok) is the national dish of Uzbekistan. Shashlik (Central Asian kebab). Manti (large steamed dumplings, similar to Chinese). Non (tandoor flatbread). Very cumin-forward. Carrots in almost every rice dish.",
    },

    # ── Modern / Fusion ───────────────────────────────────────────────────
    {
        "name": "Modern American",
        "region": "North America",
        "description": "Farm-to-table ethos with global influences. Ingredient-driven and technique-eclectic.",
        "key_ingredients": ["heirloom vegetables", "craft charcuterie", "local dairy", "foraged herbs"],
        "key_techniques": ["nose-to-tail butchery", "fermentation", "open-fire grilling"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["varies by season and chef"],
        "differentiating_factors": "Farm-to-table language on menu (local, seasonal, foraged). Eclectic influences (no single ethnic cuisine). Craft charcuterie boards. Open-fire cooking. Small plates. Changing seasonal menu. This is the catch-all for upscale American restaurants without a specific ethnic identity.",
    },
    {
        "name": "Omakase / Japanese Kaiseki",
        "region": "East Asia",
        "sub_region": "Japan",
        "description": "Chef-curated multi-course seasonal meal. Every course reflects the moment and ingredients.",
        "key_ingredients": ["dashi", "seasonal fish", "wasabi", "rice", "tofu", "miso"],
        "key_techniques": ["kaiseki sequencing", "sashimi knife work", "dashi extraction"],
        "flavor_profile": {"umami": 5, "sweet": 2, "salty": 2, "sour": 2, "spicy": 1},
        "typical_dishes": ["omakase sushi", "kaiseki multi-course", "kappo"],
        "differentiating_factors": "Omakase = chef's choice, no menu shown, counter seating, 8–20 courses. Kaiseki = multi-course formal Japanese seasonal meal. If the menu says 'omakase', 'chef's selection', 'kappo', 'kaiseki' and is Japanese = this profile. Distinct from standard Japanese by the format and price point.",
    },
    {
        "name": "Dim Sum",
        "region": "East Asia",
        "sub_region": "Cantonese",
        "description": "Tea-house small-plate tradition — steamed, fried, and baked bites with tea pairing.",
        "key_ingredients": ["shrimp", "pork", "rice flour", "taro", "lotus leaf", "XO sauce"],
        "key_techniques": ["bamboo steaming", "har gow folding", "char siu bao baking"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 1, "spicy": 1},
        "typical_dishes": ["har gow", "siu mai", "char siu bao", "turnip cake", "egg tart"],
        "differentiating_factors": "Dim sum is identified by the FORMAT: many small bamboo steamer baskets, trolley service or checklist ordering, har gow (shrimp dumplings in translucent wrapper), siu mai (open-top pork dumplings), char siu bao (BBQ pork buns). Always Cantonese. Tea (yum cha) served with food.",
    },

    # ── Pacific & Oceania ─────────────────────────────────────────────────
    {
        "name": "Hawaiian / Pacific Fusion",
        "region": "Pacific",
        "description": "Polynesian, Japanese, and American layers. Poke and plate lunches are iconic.",
        "key_ingredients": ["tuna", "macadamia", "taro", "soy sauce", "lilikoi (passion fruit)", "spam"],
        "key_techniques": ["poke seasoning", "imu underground oven", "malasada frying"],
        "flavor_profile": {"umami": 4, "sweet": 3, "salty": 3, "sour": 2, "spicy": 1},
        "typical_dishes": ["poke bowl", "kalua pork", "loco moco", "shave ice", "spam musubi"],
        "differentiating_factors": "Poke bowl (raw tuna + soy + sesame + rice) is the primary signal. Spam musubi (Spam + rice wrapped in nori). Loco moco (rice + hamburger patty + fried egg + gravy). Plate lunch format. Macadamia nuts. Shave ice (not snow cone). Japanese + Polynesian + American fusion.",
    },

    # ── More Asian ────────────────────────────────────────────────────────
    {
        "name": "Taiwanese",
        "region": "East Asia",
        "sub_region": "Taiwan",
        "description": "Night market snack culture meets Japanese influence. Beef noodle soup is the national dish.",
        "key_ingredients": ["soy sauce", "sesame oil", "five spice", "oyster", "pork belly", "taro"],
        "key_techniques": ["night market frying", "braised pork (lu rou)", "beef noodle long-simmering"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["beef noodle soup", "lu rou fan", "oyster vermicelli", "scallion pancake", "boba"],
        "differentiating_factors": "Taiwanese beef noodle soup (braised beef + broad noodles in spiced broth) is the national dish. Lu rou fan (braised pork rice). Oyster vermicelli. Boba/bubble tea. Night market snacks (popcorn chicken, stinky tofu). Japanese-influenced (Japanese rule 1895–1945) = cleaner flavors than mainland Chinese.",
    },
    {
        "name": "Burmese (Myanmar)",
        "region": "Southeast Asia",
        "description": "Indian, Chinese, and Thai crossroads. Lahpet (fermented tea leaf) salad is unique.",
        "key_ingredients": ["fermented tea leaf", "fish paste", "turmeric", "chickpea flour", "tamarind"],
        "key_techniques": ["salad tossing (thoke)", "mohinga noodle-souping", "curry oil-separating"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 3, "spicy": 3},
        "typical_dishes": ["mohinga", "lahpet thoke", "shan noodles", "mont di", "burmese curry"],
        "differentiating_factors": "Lahpet thoke (fermented tea leaf salad with nuts) is completely unique to Burma — no other cuisine has it. Mohinga (catfish + lemongrass noodle soup, national dish). Shan noodles (tomato-based). Oil-separated curries (oil pools on top intentionally). Turmeric heavy.",
    },
    {
        "name": "Bangladeshi / Bengali",
        "region": "South Asia",
        "description": "Fish and rice culture; mustard oil, panch phoron, and hilsa are quintessential.",
        "key_ingredients": ["mustard oil", "hilsa fish", "panch phoron", "turmeric", "green chili"],
        "key_techniques": ["bhorta (mashing)", "bhuna (dry-fry)", "jhol (light curry)"],
        "flavor_profile": {"umami": 3, "sweet": 2, "salty": 3, "sour": 3, "spicy": 4},
        "typical_dishes": ["hilsa curry", "shorshe ilish", "mishti doi", "panta bhat", "bhapa ilish"],
        "differentiating_factors": "Hilsa fish (shorshe ilish = hilsa in mustard sauce) is the most prized and distinctive dish. Mustard oil (pungent, raw-tasting oil) is the cooking fat. Panch phoron (five-spice blend unique to Bengal). Mishti doi (sweetened yogurt). Strong mustard flavor throughout.",
    },
    {
        "name": "Nepali / Tibetan",
        "region": "South Asia",
        "description": "High-altitude cuisine: momos (dumplings), dal bhat, and butter tea.",
        "key_ingredients": ["timur pepper", "fenugreek", "ghee", "yak butter", "lentils", "tsampa"],
        "key_techniques": ["momo folding and steaming", "dal bhat assembly", "thukpa noodle-souping"],
        "flavor_profile": {"umami": 2, "sweet": 1, "salty": 3, "sour": 2, "spicy": 3},
        "typical_dishes": ["momos", "dal bhat", "thukpa", "sel roti", "gundruk"],
        "differentiating_factors": "Momos (steamed dumplings, similar to Chinese but with different filling/wrapper) are the primary signal. Dal bhat (lentil soup + rice, eaten twice daily). Thukpa (Tibetan noodle soup). Timur pepper (Nepali relative of Sichuan peppercorn). Butter tea (salt + butter + tea = Tibetan).",
    },
    {
        "name": "Laotian",
        "region": "Southeast Asia",
        "description": "Landlocked cousin to Thai and Vietnamese; sticky rice, fermented fish paste, and larb.",
        "key_ingredients": ["sticky rice", "padaek", "dill", "lemongrass", "galangal", "kaffir lime"],
        "key_techniques": ["bamboo sticky rice steaming", "larb (raw-meat salad)", "jeow (dipping sauce)"],
        "flavor_profile": {"umami": 4, "sweet": 1, "salty": 4, "sour": 3, "spicy": 3},
        "typical_dishes": ["larb", "khao niao", "or lam", "tam mak hoong", "khao poon"],
        "differentiating_factors": "Sticky rice (khao niao) eaten with EVERY meal, used as utensil. Padaek (unfiltered fermented fish paste, stronger than Thai fish sauce). Larb (minced meat salad, very similar to Isaan Thai). Dill in savory dishes (unusual in SE Asia). Or lam (Luang Prabang stew with sakhaan bark).",
    },
    {
        "name": "Cambodian (Khmer)",
        "region": "Southeast Asia",
        "description": "Subtle and aromatic; kroeung spice paste and prahok (fermented fish) are the backbone.",
        "key_ingredients": ["kroeung paste", "prahok", "coconut milk", "galangal", "kaffir lime", "turmeric"],
        "key_techniques": ["amok steaming in banana leaf", "kroeung paste pounding"],
        "flavor_profile": {"umami": 4, "sweet": 2, "salty": 3, "sour": 2, "spicy": 2},
        "typical_dishes": ["fish amok", "lok lak", "bai sach chrouk", "num banh chok", "samlor korkor"],
        "differentiating_factors": "Fish amok (coconut milk + kroeung paste curry steamed in banana leaf) is the national dish and unique identifier. Prahok (extremely pungent fermented fish paste) used as seasoning base. Kroeung (lemongrass-based yellow/red/green paste). Milder and more subtle than Thai or Vietnamese.",
    },
    {
        "name": "Pakistani",
        "region": "South Asia",
        "description": "Robust spicing, karahi cooking, and tandoor. Heavily meat-forward with Mughal heritage.",
        "key_ingredients": ["garam masala", "yogurt", "ghee", "karahi (wok)", "green chili", "lamb"],
        "key_techniques": ["karahi cooking", "dum biryani", "nihari slow stewing"],
        "flavor_profile": {"umami": 2, "sweet": 1, "salty": 3, "sour": 2, "spicy": 4},
        "typical_dishes": ["nihari", "karahi", "biryani", "seekh kebab", "haleem", "saag"],
        "differentiating_factors": "Nihari (slow-cooked beef/lamb shank stew, eaten for breakfast) is distinctly Pakistani. Karahi (tomato + ginger + green chili + yogurt wok dish). Haleem (wheat + meat porridge). More meat-forward and spicier than North Indian. No paneer/cream-heavy dishes. Seekh kebab (ground meat on skewer, heavily spiced).",
    },
]
